fruits = [
    "Apple",
    "Banana",
    "Mango",
    "Strawberry",
    "Pineapple",
    "Watermelon",
    "Kiwi",
    "Grapes",
    "Papaya",
    "Pomegranate",
    "Orange",
    "Peach",
    "Plum",
    "Cherry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Lemon",
    "Lime",
    "Coconut",
    "Apricot",
    "Avocado",
    "Cantaloupe",
    "Dragonfruit",
    "Guava",
    "Jackfruit",
    "Lychee",
    "Passionfruit",
    "Pear",
    "Fig",
    "Tangerine",
    "Nectarine",
    "Quince",
    "Persimmon",
    "Rambutan",
    "Durian",
    "Mulberry",
    "Cranberry",
    "Elderberry",
    "Gooseberry",
    "Soursop",
    "Starfruit"
]

languages = [
    "English",
    "Mandarin Chinese",
    "Hindi",
    "Spanish",
    "French",
    "Arabic",
    "Bengali",
    "Russian",
    "Portuguese",
    "Urdu",
    "Indonesian",
    "German",
    "Japanese",
    "Lahnda (Western Punjabi)",
    "Telugu",
    "Marathi",
    "Tamil",
    "Turkish",
    "Korean",
    "Vietnamese",
    "Italian",
    "Hausa",
    "Thai",
    "Gujarati",
    "Javanese",
    "Kannada",
    "Persian (Farsi)",
    "Polish",
    "Ukrainian",
    "Malayalam",
    "Oriya (Odia)",
    "Burmese",
    "Romanian",
    "Sundanese",
    "Cebuano",
    "Dutch",
    "Igbo",
    "Amharic",
    "Yoruba",
    "Tagalog",
    "Haitian Creole",
    "Serbo-Croatian",
    "Sinhala",
    "Khmer",
    "Nepali",
    "Assamese",
    "Chhattisgarhi",
    "Madurese",
    "Somali",
    "Hmong"
]

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Congo (Democratic Republic of the)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. Swaziland)",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea (North)",
    "Korea (South)",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

movies = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "The Godfather: Part II",
    "12 Angry Men",
    "Schindler's List",
    "The Lord of the Rings: The Return of the King",
    "Pulp Fiction",
    "The Good, the Bad and the Ugly",
    "Fight Club",
    "Forrest Gump",
    "Inception",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Matrix",
    "Goodfellas",
    "One Flew Over the Cuckoo's Nest",
    "Se7en",
    "The Silence of the Lambs",
    "City of God",
    "It's a Wonderful Life",
    "Saving Private Ryan",
    "The Green Mile",
    "Interstellar",
    "Life Is Beautiful",
    "Star Wars: Episode IV - A New Hope",
    "Spirited Away",
    "The Usual Suspects",
    "The Lion King",
    "The Pianist",
    "The Departed",
    "Gladiator",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "Whiplash",
    "The Prestige",
    "The Intouchables",
    "The Lord of the Rings: The Two Towers",
    "Alien",
    "Psycho",
    "American History X",
    "The Dark Knight Rises",
    "Django Unchained",
    "WALL-E",
    "The Shining",
    "Memento",
    "Apocalypse Now",
    "Indiana Jones and the Raiders of the Lost Ark",
    "The Great Dictator",
    "Avengers: Infinity War",
    "Grave of the Fireflies",
    "Sunset Blvd.",
    "Oldboy",
    "Once Upon a Time in the West",
    "Princess Mononoke",
    "Casablanca",
    "Cinema Paradiso",
    "Rear Window",
    "City Lights",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Modern Times",
    "Coco",
    "Aliens",
    "Your Name",
    "Toy Story",
    "Braveheart",
    "Reservoir Dogs",
    "Amadeus",
    "Like Stars on Earth",
    "Inglourious Basterds",
    "3 Idiots",
    "Good Will Hunting",
    "Requiem for a Dream",
    "Singin' in the Rain",
    "The Hunt",
    "The Apartment",
    "A Clockwork Orange",
    "Double Indemnity",
    "Taxi Driver",
    "Lawrence of Arabia",
    "Eternal Sunshine of the Spotless Mind",
    "Amélie",
    "To Kill a Mockingbird",
    "Scarface",
    "The Sting",
    "The Elephant Man",
    "The Kid",
    "Full Metal Jacket",
    "Bicycle Thieves",
    "2001: A Space Odyssey",
    "In the Name of the Father",
    "The Wolf of Wall Street",
    "The Truman Show",
    "Ben-Hur",
    "Shutter Island",
    "Jurassic Park",
    "A Separation",
    "Hotel Rwanda",
    "The Sixth Sense",
    "Pan's Labyrinth",
    "V for Vendetta",
    "No Country for Old Men",
    "Dead Poets Society",
    "Platoon",
    "The Big Lebowski",
    "Kill Bill: Vol. 1",
    "Finding Nemo",
    "Ratatouille",
    "Die Hard",
    "Heat",
    "Snatch",
    "Donnie Darko",
    "The Avengers",
    "Blade Runner 2049",
    "Inside Out",
    "A Beautiful Mind",
    "The Social Network",
    "The Bourne Ultimatum",
    "Casino",
    "Slumdog Millionaire",
    "Gandhi",
    "The Grand Budapest Hotel",
    "Her",
    "Prisoners",
    "Guardians of the Galaxy",
    "The Imitation Game",
    "Dallas Buyers Club",
    "The King's Speech",
    "The Revenant",
    "1917",
    "The Hateful Eight",
    "Black Swan",
    "The Curious Case of Benjamin Button",
    "Catch Me If You Can",
    "The Pursuit of Happyness",
    "Avatar",
    "Mad Max: Fury Road",
    "Logan",
    "The Shape of Water",
    "Argo",
    "Les Misérables",
    "12 Years a Slave",
    "Dune",
    "The Irishman",
    "Crouching Tiger, Hidden Dragon",
    "Birdman",
    "Little Miss Sunshine",
    "Knives Out"
]